eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false